# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
baseurl:
# It will redirect your site to this url
url                 : https://blog.allmwh.org
title               : allmwh's story
name                : allmwh
subtitle            : "Biochem by degree, Programmer by life"
description         : "description something"
repository          : allmwh/allmwh.github.io
keywords            : allmwh, jonas870103, 何玟霖,allmwh0103
date_format         : "ordinal"
timezone            : Asia/Taipei
encoding            : "utf-8"
side_bar_repo_limit : 3

author              : allmwh
github_username     : allmwh
location            : Keelung, Taiwan
email               : jonas870103@gmail.com

markdown            : kramdown
kramdown:
  input             : GFM
highlighter         : rouge
paginate            : 12
lsi                 : false
quiet               : false
future              : true
excerpt_separator   : <!--more-->                # 摘录的分隔符
permalink           : /:year-:month/:title    # 博文发布的 URL，伪静态
plugins:
  - jekyll-github-metadata                  # github 元信息
  - rouge
  - jekyll-octicons                         # 支持 octions 图标
  - jekyll-paginate                         # 分页
  - jekyll-feed                             # 自动生成 SSR 源
  - jemoji                                  # 解析 emoji
  - jekyll-sitemap                          # 自动生成 sitemap
  - jekyll-seo-tag                          # 自动 SEO 头信息生成
#   - jekyll-html-pipeline                  #
#   - jekyll-mentions                       # 用于 @github 用户
#collections:
  #wiki:
  #  output          : true
  #  permalink       : /wiki/:path.html
  #design-mode: 
  #  output          : true
  #  permalink       : /design-mode/:path.html



# 导航
navs:
  -
    href            : /
    label           : 首頁

  -
    href            : /categories/
    label           : 分類

# -
#   href            : /archives/
#   label           : 歸檔

#  -
#    href            : /wiki/
#    label           : 维基

#  -
#    href            : /links/
#    label           : 链接

  -
    href            : /about/
    label           : 關於

subscribe_rss       : /feed.xml


# 评论模块
comments_provider: disqus
disqus:
  username: allmwh-blog
#lazy_load_disqus : false
# gitalk:
#   owner             : zoharyips
#   repo              : blog-comments
#   clientID          : 4f7905fa91963e1cb585
#   clientSecret      : 860aa59b9dac0ff81e468c3a67bec5a052e8b8ec

# 站内搜索
simple_jekyll_search:
  fulltext          : false

# leanCloud 访问统计
#leancloud:
# enable: true
# app_id: 7EiyLoiTRMpJGKx5Jyy6FV0S-gzGzoHsz
# app_key: 0l02blBLDj6noCkLMoF76LD8
# class_name: visited_times

# 谷歌分析
google:
  analytics_id      : UA-157884523-1

# 备案号
#beian               : 粤ICP备18146252号-1
#MIIT                : http://www.beian.miit.gov.cn

#分享功能
sharing:
  provider: addthis
  addthis:
    id: ra-5e3ae037d5894c86